# Generated by Django 3.1.6 on 2021-02-06 02:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('boleta', models.CharField(max_length=10, verbose_name='Boleta')),
                ('escuela', models.CharField(max_length=50, verbose_name='Escuela')),
                ('carrera', models.CharField(max_length=50, verbose_name='Carrera')),
                ('descripcion', ckeditor.fields.RichTextField(default='Ninguna')),
                ('fecha_registro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
