# Generated by Django 3.1.6 on 2021-02-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='boleta',
            field=models.CharField(max_length=10, unique=True, verbose_name='Boleta'),
        ),
    ]
